/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth.index'
import { Route as AuthOnboardingRouteImport } from './routes/_auth.onboarding'
import { Route as AuthSitesSiteIdRouteImport } from './routes/_auth.sites.$siteId'
import { Route as AuthSitesSiteIdIndexRouteImport } from './routes/_auth.sites.$siteId.index'
import { Route as AuthSitesSiteIdAccessRouteImport } from './routes/_auth.sites.$siteId.access'
import { Route as AuthSitesSiteIdAdminRouteImport } from './routes/_auth.sites.$siteId.admin'
import { Route as AuthSitesSiteIdEditorRouteImport } from './routes/_auth.sites.$siteId.editor'
import { Route as AuthSitesSiteIdLeadsRouteImport } from './routes/_auth.sites.$siteId.leads'
import { Route as AuthSitesSiteIdTemplatesRouteImport } from './routes/_auth.sites.$siteId.templates'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSitesSiteIdRoute = AuthSitesSiteIdRouteImport.update({
  id: '/sites/$siteId',
  path: '/sites/$siteId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSitesSiteIdIndexRoute = AuthSitesSiteIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSitesSiteIdRoute,
} as any)
const AuthSitesSiteIdAccessRoute = AuthSitesSiteIdAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AuthSitesSiteIdRoute,
} as any)
const AuthSitesSiteIdAdminRoute = AuthSitesSiteIdAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthSitesSiteIdRoute,
} as any)
const AuthSitesSiteIdEditorRoute = AuthSitesSiteIdEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => AuthSitesSiteIdRoute,
} as any)
const AuthSitesSiteIdLeadsRoute = AuthSitesSiteIdLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthSitesSiteIdRoute,
} as any)
const AuthSitesSiteIdTemplatesRoute =
  AuthSitesSiteIdTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthSitesSiteIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/sites/$siteId': typeof AuthSitesSiteIdRouteWithChildren
  '/sites/$siteId/access': typeof AuthSitesSiteIdAccessRoute
  '/sites/$siteId/admin': typeof AuthSitesSiteIdAdminRoute
  '/sites/$siteId/editor': typeof AuthSitesSiteIdEditorRoute
  '/sites/$siteId/leads': typeof AuthSitesSiteIdLeadsRoute
  '/sites/$siteId/templates': typeof AuthSitesSiteIdTemplatesRoute
  '/sites/$siteId/': typeof AuthSitesSiteIdIndexRoute
}
export interface FileRoutesByTo {
  '/onboarding': typeof AuthOnboardingRoute
  '/': typeof AuthIndexRoute
  '/sites/$siteId/access': typeof AuthSitesSiteIdAccessRoute
  '/sites/$siteId/admin': typeof AuthSitesSiteIdAdminRoute
  '/sites/$siteId/editor': typeof AuthSitesSiteIdEditorRoute
  '/sites/$siteId/leads': typeof AuthSitesSiteIdLeadsRoute
  '/sites/$siteId/templates': typeof AuthSitesSiteIdTemplatesRoute
  '/sites/$siteId': typeof AuthSitesSiteIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/onboarding': typeof AuthOnboardingRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/sites/$siteId': typeof AuthSitesSiteIdRouteWithChildren
  '/_auth/sites/$siteId/access': typeof AuthSitesSiteIdAccessRoute
  '/_auth/sites/$siteId/admin': typeof AuthSitesSiteIdAdminRoute
  '/_auth/sites/$siteId/editor': typeof AuthSitesSiteIdEditorRoute
  '/_auth/sites/$siteId/leads': typeof AuthSitesSiteIdLeadsRoute
  '/_auth/sites/$siteId/templates': typeof AuthSitesSiteIdTemplatesRoute
  '/_auth/sites/$siteId/': typeof AuthSitesSiteIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/sites/$siteId'
    | '/sites/$siteId/access'
    | '/sites/$siteId/admin'
    | '/sites/$siteId/editor'
    | '/sites/$siteId/leads'
    | '/sites/$siteId/templates'
    | '/sites/$siteId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/onboarding'
    | '/'
    | '/sites/$siteId/access'
    | '/sites/$siteId/admin'
    | '/sites/$siteId/editor'
    | '/sites/$siteId/leads'
    | '/sites/$siteId/templates'
    | '/sites/$siteId'
  id:
    | '__root__'
    | '/_auth'
    | '/_auth/onboarding'
    | '/_auth/'
    | '/_auth/sites/$siteId'
    | '/_auth/sites/$siteId/access'
    | '/_auth/sites/$siteId/admin'
    | '/_auth/sites/$siteId/editor'
    | '/_auth/sites/$siteId/leads'
    | '/_auth/sites/$siteId/templates'
    | '/_auth/sites/$siteId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/onboarding': {
      id: '/_auth/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sites/$siteId': {
      id: '/_auth/sites/$siteId'
      path: '/sites/$siteId'
      fullPath: '/sites/$siteId'
      preLoaderRoute: typeof AuthSitesSiteIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sites/$siteId/': {
      id: '/_auth/sites/$siteId/'
      path: '/'
      fullPath: '/sites/$siteId/'
      preLoaderRoute: typeof AuthSitesSiteIdIndexRouteImport
      parentRoute: typeof AuthSitesSiteIdRoute
    }
    '/_auth/sites/$siteId/access': {
      id: '/_auth/sites/$siteId/access'
      path: '/access'
      fullPath: '/sites/$siteId/access'
      preLoaderRoute: typeof AuthSitesSiteIdAccessRouteImport
      parentRoute: typeof AuthSitesSiteIdRoute
    }
    '/_auth/sites/$siteId/admin': {
      id: '/_auth/sites/$siteId/admin'
      path: '/admin'
      fullPath: '/sites/$siteId/admin'
      preLoaderRoute: typeof AuthSitesSiteIdAdminRouteImport
      parentRoute: typeof AuthSitesSiteIdRoute
    }
    '/_auth/sites/$siteId/editor': {
      id: '/_auth/sites/$siteId/editor'
      path: '/editor'
      fullPath: '/sites/$siteId/editor'
      preLoaderRoute: typeof AuthSitesSiteIdEditorRouteImport
      parentRoute: typeof AuthSitesSiteIdRoute
    }
    '/_auth/sites/$siteId/leads': {
      id: '/_auth/sites/$siteId/leads'
      path: '/leads'
      fullPath: '/sites/$siteId/leads'
      preLoaderRoute: typeof AuthSitesSiteIdLeadsRouteImport
      parentRoute: typeof AuthSitesSiteIdRoute
    }
    '/_auth/sites/$siteId/templates': {
      id: '/_auth/sites/$siteId/templates'
      path: '/templates'
      fullPath: '/sites/$siteId/templates'
      preLoaderRoute: typeof AuthSitesSiteIdTemplatesRouteImport
      parentRoute: typeof AuthSitesSiteIdRoute
    }
  }
}

interface AuthSitesSiteIdRouteChildren {
  AuthSitesSiteIdAccessRoute: typeof AuthSitesSiteIdAccessRoute
  AuthSitesSiteIdAdminRoute: typeof AuthSitesSiteIdAdminRoute
  AuthSitesSiteIdEditorRoute: typeof AuthSitesSiteIdEditorRoute
  AuthSitesSiteIdLeadsRoute: typeof AuthSitesSiteIdLeadsRoute
  AuthSitesSiteIdTemplatesRoute: typeof AuthSitesSiteIdTemplatesRoute
  AuthSitesSiteIdIndexRoute: typeof AuthSitesSiteIdIndexRoute
}

const AuthSitesSiteIdRouteChildren: AuthSitesSiteIdRouteChildren = {
  AuthSitesSiteIdAccessRoute: AuthSitesSiteIdAccessRoute,
  AuthSitesSiteIdAdminRoute: AuthSitesSiteIdAdminRoute,
  AuthSitesSiteIdEditorRoute: AuthSitesSiteIdEditorRoute,
  AuthSitesSiteIdLeadsRoute: AuthSitesSiteIdLeadsRoute,
  AuthSitesSiteIdTemplatesRoute: AuthSitesSiteIdTemplatesRoute,
  AuthSitesSiteIdIndexRoute: AuthSitesSiteIdIndexRoute,
}

const AuthSitesSiteIdRouteWithChildren = AuthSitesSiteIdRoute._addFileChildren(
  AuthSitesSiteIdRouteChildren,
)

interface AuthRouteChildren {
  AuthOnboardingRoute: typeof AuthOnboardingRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthSitesSiteIdRoute: typeof AuthSitesSiteIdRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthOnboardingRoute: AuthOnboardingRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthSitesSiteIdRoute: AuthSitesSiteIdRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
